### ISSUE TITLE
Update to python37 runtime

### ISSUE THREAD

**Issue by chriscalo** [chriscalo/gae-python-starter#1]
From https://cloud.google.com/appengine/docs/standard/python3/config/appref:

``` yaml
runtime: python37

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
```
